/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`audiofile` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `audiofile`;

DROP TABLE IF EXISTS `Album`;

CREATE TABLE `Album` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `cover art` BLOB NOT NULL,
  `publisher` varchar(50) NOT NULL,
  `publish date` DATE NOT NULL,
  
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Album-Group`;

CREATE TABLE `Album-Group` (
  `album ID` int(11) NOT NULL,
  `group ID` int(11) NOT NULL,
  
  FOREIGN KEY (`album ID`)
      REFERENCES `Album`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE,

  FOREIGN KEY (`group ID`)
      REFERENCES `Group`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Album-Song`;

CREATE TABLE `Album-Song` (
  `album ID` int(11) NOT NULL,
  `song ID` int(11) NOT NULL,
  
  FOREIGN KEY (`album ID`)
      REFERENCES `Album`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE,

  FOREIGN KEY (`song ID`)
      REFERENCES `Song`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Genre`;

CREATE TABLE `Genre` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Genre-Album`;

CREATE TABLE `Genre-Album` (
  `genre ID` int(11) NOT NULL,
  `album ID` int(11) NOT NULL,

  FOREIGN KEY (`genre ID`)
      REFERENCES `Genre`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE,
  
  FOREIGN KEY (`album ID`)
      REFERENCES `Album`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Genre-Group`;

CREATE TABLE `Genre-Group` (
  `genre ID` int(11) NOT NULL,
  `group ID` int(11) NOT NULL,

  FOREIGN KEY (`genre ID`)
      REFERENCES `Genre`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE,
  
  FOREIGN KEY (`group ID`)
      REFERENCES `Group`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Group`;

CREATE TABLE `Group` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `numberOfMembers` int(11) NOT NULL,
  
  PRIMARY KEY (`ID`)
  
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Group-Song`;

CREATE TABLE `Group-Song` (
  `group ID` int(11) NOT NULL,
  `song ID` int(11) NOT NULL,
  
  FOREIGN KEY (`group ID`)
      REFERENCES `Group`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE,

  FOREIGN KEY (`song ID`)
      REFERENCES `Song`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Related Genres`;

CREATE TABLE `Related Genres` (
  `genre1` int(11) NOT NULL,
  `genre2` int(11) NOT NULL,
  
  FOREIGN KEY (`genre1`)
      REFERENCES `Genre`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE,

  FOREIGN KEY (`genre2`)
      REFERENCES `Genre`(`ID`)
      ON UPDATE CASCADE ON DELETE CASCADE
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Song`;

CREATE TABLE `Song` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `explicit?` boolean,
  `file` blob,
  
  PRIMARY KEY (`ID`)
  
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
  